version: '3.7'

services:
  web.react.app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 7015:80